CREATE TABLE types (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80)
);
--;;
CREATE INDEX types_name ON types (name);
--;;
CREATE TABLE owners (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(30),
  last_name  VARCHAR_IGNORECASE(30),
  address    VARCHAR(255),
  city       VARCHAR(80),
  telephone  VARCHAR(20)
);
--;;
CREATE INDEX owners_last_name ON owners (last_name);
--;;
CREATE TABLE pets (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(30),
  birth_date DATE,
  type_id    INTEGER NOT NULL,
  owner_id   INTEGER
);
--;;
ALTER TABLE pets ADD CONSTRAINT fk_pets_owners FOREIGN KEY (owner_id) REFERENCES owners (id);
--;;
ALTER TABLE pets ADD CONSTRAINT fk_pets_types FOREIGN KEY (type_id) REFERENCES types (id);
--;;
CREATE INDEX pets_name ON pets (name);
--;;
INSERT INTO types VALUES (default, 'cat');
--;;
INSERT INTO types VALUES (default, 'dog');
--;;
INSERT INTO types VALUES (default, 'lizard');
--;;
INSERT INTO types VALUES (default, 'snake');
--;;
INSERT INTO types VALUES (default, 'bird');
--;;
INSERT INTO types VALUES (default, 'hamster');
--;;

INSERT INTO owners VALUES (default, 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023');
--;;
INSERT INTO owners VALUES (default, 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749');
--;;
INSERT INTO owners VALUES (default, 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763');
--;;
INSERT INTO owners VALUES (default, 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198');
--;;
INSERT INTO owners VALUES (default, 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765');
--;;
INSERT INTO owners VALUES (default, 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654');
--;;
INSERT INTO owners VALUES (default, 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387');
--;;
INSERT INTO owners VALUES (default, 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683');
--;;
INSERT INTO owners VALUES (default, 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435');
--;;
INSERT INTO owners VALUES (default, 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487');
--;;

INSERT INTO pets VALUES (default, 'Leo', '2010-09-07', 1, 1);
--;;
INSERT INTO pets VALUES (default, 'Basil', '2012-08-06', 6, 2);
--;;
INSERT INTO pets VALUES (default, 'Rosy', '2011-04-17', 2, 3);
--;;
INSERT INTO pets VALUES (default, 'Jewel', '2010-03-07', 2, 3);
--;;
INSERT INTO pets VALUES (default, 'Iggy', '2010-11-30', 3, 4);
--;;
INSERT INTO pets VALUES (default, 'George', '2010-01-20', 4, 5);
--;;
INSERT INTO pets VALUES (default, 'Samantha', '2012-09-04', 1, 6);
--;;
INSERT INTO pets VALUES (default, 'Max', '2012-09-04', 1, 6);
--;;
INSERT INTO pets VALUES (default, 'Lucky', '2011-08-06', 5, 7);
--;;
INSERT INTO pets VALUES (default, 'Mulligan', '2007-02-24', 2, 8);
--;;
INSERT INTO pets VALUES (default, 'Freddy', '2010-03-09', 5, 9);
--;;
INSERT INTO pets VALUES (default, 'Lucky', '2010-06-24', 2, 10);
--;;
INSERT INTO pets VALUES (default, 'Sly', '2012-06-08', 1, 10);
--;;
