CREATE TABLE specialties (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80)
);
--;;
CREATE INDEX specialties_name ON specialties (name);
--;;
CREATE TABLE vet_specialties (
  vet_id       INTEGER NOT NULL,
  specialty_id INTEGER NOT NULL
);
--;;
ALTER TABLE vet_specialties ADD CONSTRAINT fk_vet_specialties_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
--;;
ALTER TABLE vet_specialties ADD CONSTRAINT fk_vet_specialties_specialties FOREIGN KEY (specialty_id) REFERENCES specialties (id);
--;;
INSERT INTO specialties VALUES (default, 'radiology');
--;;
INSERT INTO specialties VALUES (default, 'surgery');
--;;
INSERT INTO specialties VALUES (default, 'dentistry');
--;;
INSERT INTO vet_specialties VALUES (2, 1);
--;;
INSERT INTO vet_specialties VALUES (3, 2);
--;;
INSERT INTO vet_specialties VALUES (3, 3);
--;;
INSERT INTO vet_specialties VALUES (4, 2);
--;;
INSERT INTO vet_specialties VALUES (5, 1);
