CREATE TABLE visits (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pet_id      INTEGER,
  visit_date  DATE,
  description VARCHAR(255)
);
--;;
ALTER TABLE visits ADD CONSTRAINT fk_visits_pets FOREIGN KEY (pet_id) REFERENCES pets (id);
--;;
CREATE INDEX visits_pet_id ON visits (pet_id);
--;;
INSERT INTO visits VALUES (default, 7, '2013-01-01', 'rabies shot');
--;;
INSERT INTO visits VALUES (default, 8, '2013-01-02', 'rabies shot');
--;;
INSERT INTO visits VALUES (default, 8, '2013-01-03', 'neutered');
--;;
INSERT INTO visits VALUES (default, 7, '2013-01-04', 'spayed');
--;;
