name: Deploy-To-AppService

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Install Clojure CLI and deps
      run: |
        sudo apt update && DEBIAN_FRONTEND=noninteractive sudo apt install -y --no-install-recommends \
          curl \
          make \
          openjdk-17-jdk-headless \
          rlwrap
        curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
        chmod +x linux-install.sh
        sudo ./linux-install.sh
        make uberjar

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        package: 'target/petclinic-standalone.jar'
        type: jar
        clean: true