name: Deploy-To-AppService

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'microsoft'

    - name: Install Clojure CLI and deps
      run: |
        sudo apt update && DEBIAN_FRONTEND=noninteractive sudo apt install -y --no-install-recommends \
          curl \
          make \
          rlwrap
        curl -L -o /tmp/linux-install.sh https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
        chmod +x /tmp/linux-install.sh
        sudo /tmp/linux-install.sh
        clj -M:test
        make clean uberjar

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        package: 'target/petclinic-standalone.jar'
        type: jar
        clean: true